os: linux
dist: trusty
language: python
python:
  - "3.5"
  - "3.6"
cache:
  - apt
  - pip
env:
  global:
    - PIP_INSTALL="pip install"
    - DISCID="$PIP_INSTALL discid" MUTAGEN="$PIP_INSTALL mutagen>=1.37"
    - BABEL="$PIP_INSTALL babel"
    - NOSE="$PIP_INSTALL nose2"
    - COVERAGE="$PIP_INSTALL nose-cov"
    - CODACY="$PIP_INSTALL codacy-coverage"
  matrix:
    - PYQT="$PIP_INSTALL pyqt5==5.7.1"
    - PYQT="$PIP_INSTALL pyqt5==5.8"
    - PYQT="$PIP_INSTALL pyqt5==5.8.1.1"
    - PYQT="$PIP_INSTALL pyqt5==5.8.2"

before_install:
  - sudo apt-get update -qq && sudo apt-get install -qq transifex-client libdiscid0 libdiscid0-dev qt5-default
  - $BABEL
  - $PYQT
  - $MUTAGEN
  - $DISCID
  - $NOSE
  - $COVERAGE
  - touch ~/.transifexrc
  - printf "[https://www.transifex.com]\nhostname = https://www.transifex.com\npassword = $TX_PASSWORD\ntoken =\nusername = $TX_USERNAME" > ~/.transifexrc
install:
  # Set up Picard
  - python setup.py clean
  - python setup.py clean_ui
  - python setup.py build_ui
  - python setup.py build_ext -i
  - python setup.py regen_pot_file
  - git diff --stat --exit-code
  - 'if [ ! -z "${TX_PASSWORD}" ]; then python setup.py get_po_files; fi'
  - 'if [ ! -z "${TX_PASSWORD}" ]; then python setup.py update_constants; fi'
  - python setup.py build_locales -i
  - python setup.py patch_version --platform=test
  - python setup.py install
# Run the tests!
script: "nose2 -v --with-coverage --coverage picard --coverage-report xml"
after_success:
  - 'if [ ! -z "${CODACY_PROJECT_TOKEN}" ]; then $CODACY; python-codacy-coverage -r coverage.xml; fi'
# Tell people that tests were run
